<?php

/**
 * @file
 * Contains metsis_search.module for drupal8.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\Plugin\views\cache\CachePluginBase;


/**
 * Implements hook_help().
 */
function metsis_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the metsis_search module.
    case 'help.page.metsis_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('METSIS Metadata Search') . '</p>';
      return $output;

    default:
  }
}

/**
* Implements hook_views_pre_render().
*
* Adding  our custom css to the search view
*/
function metsis_search_views_pre_render(ViewExecutable $view) {
  if (isset($view) && ($view->storage->id() == 'metsis_search')) {
    $view->element['#attached']['library'][] = 'metsis_search/metadata_search_view';
      $view->element['#attached']['library'][] = 'metsis_search/children_count';
      $view->element['#attached']['library'][] = 'blazy/load';
      //$view->element['#attributes']['id'][] = 'children';
  }
  if (isset($view) && ($view->storage->id() == 'metsis_search')) {
      $view->element['#attached']['library'][] = 'metsis_search/metadata_search_view';
      $view->element['#attached']['library'][] = 'metsis_search/children_count';
      $view->element['#attached']['library'][] = 'blazy/load';
  }
}

/**
 * Implemets hook_theme()
 */
function metsis_search_theme() {
    \Drupal::logger('metsis_search')->debug("Enter: hook_theme");
  $tempstore = \Drupal::service('tempstore.private')->get('metsis_search');
  $bboxFilter = $tempstore->get('bboxFilter');
  $tllat = "";
  $tllon = "";
  $brlat = "";
  $brlon = "";
  if ($bboxFilter != NULL) {
    $tllat = $tempstore->get('tllat');
    $tllon = $tempstore->get('tllon');
    $brlat = $tempstore->get('brlat');
    $brlon = $tempstore->get('brlon');
  }
  return [
    'block__exposedformmetsis_search_viewresults' => [
      'render element' => 'elements',
      'base hook' => 'block',
    ],
    'views_view_fields__metsis_search_view__results' => [
      'render element' => 'elements',
      'base hook' => 'views field',
    ],
    'views_view__metsis_search_view__results' => [
      'render element' => 'elements',
      'base hook' => 'views view',
    ],
    'block__mapblockformetsissearch' => [
      'render element' => 'elements',
      'base hook' => 'block',
      'variables' => [
      /*  'tllat' => NULL,
        'tllon' => NULL,
        'brlat' => NULL,
        'brlon' => NULL,*/
        'tllat' => $tllat,
        'tllon' => $tllon,
        'brlat' => $brlat,
        'brlon' => $brlon,
      ],
      #'template' =>   'block--mapblockformetsissearch',
    ],
  ];
}

/**
 * Implments hook_views_query_alter
 */
function metsis_search_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {

  if( $view->id() == 'metsis_search') {
  //Do something withe the veiws query here

  }
}

function metsis_search_search_api_solr_query_alter(\Solarium\Core\Query\QueryInterface $solarium_query, \Drupal\search_api\Query\QueryInterface $query) {
  $tempstore = \Drupal::service('tempstore.private')->get('metsis_search');
  $bboxFilter = $tempstore->get('bboxFilter');

  //Add bbox filter query if drawn bbox on map
  \Drupal::logger('metsis_search-hook_solr_qyery_alter')->debug("bboxFilter: " . $bboxFilter);
 if($bboxFilter != NULL && $bboxFilter != "") {
   $solarium_query->createFilterQuery('bbox')->setQuery('{!field f=bbox score=overlapRatio}Contains(' . $bboxFilter . ')');
  }

  //var_dump($query);
}
/*
 * Implements hook_views_post_render.
*/
function metsis_search_views_post_render(ViewExecutable $view, &$output, CachePluginBase $cache) {
  if( $view->id() == 'metsis_search') {
  //  \Drupal::logger('metsis_search')->debug("Entering hook_views_post_render");
  }

}

function metsis_search_views_pre_build(ViewExecutable $view) {
  if( $view->id() == 'metsis_search') {
    $request = \Drupal::request();
    $query_from_request = $request->query->all();
  //Check if operator op is set in query and op=Reset to reset boundingbox
    if(isset($query_from_request['op'])) {
      if($query_from_request['op'] == "Reset") {
        \Drupal::logger('metsis_search')->debug("Got reset event..resetting bbox");
        $tempstore = \Drupal::service('tempstore.private')->get('metsis_search');
        $tempstore->delete('bboxFilter');
        $tempstore->delete('tllat');
        $tempstore->delete('tllon');
        $tempstore->delete('brlat');
        $tempstore->delete('brlon');

      }
    }

  }
}

function metsis_search_block_view_alter(array &$build, Drupal\Core\Block\BlockPluginInterface $block) {
//  if( $block->id() == 'metsis_search_map_block') {
  //  \Drupal::logger('metsis_search')->debug("Entering hook_block_alter for MapSearchBlock");
  //}
}
/**
 * Implements hook_form_alter().
 */
function metsis_search_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
//  \Drupal::logger('metsis_search')->debug("Entering hook_form_alter: form_id=" .$form_id );
//if ($form_id == 'views_exposed_form') {
//  $form['actions']['reset']['#ajax'] = [
//    'callback' => '\Drupal\metsis_search\Controller\MapSearchController::resetCallback',
//  ];
//var_dump($form);
//}
}
